// 海报配置文件
window.posterConfig = {
  title: "全门派核心助战一览",
  titleFontSize: 32,
  isTitleBold: true,
  showBg: true,
  showTextEffect: true,
  titleBgStyle: "bg-none",
  titleTextStyle: "ts-blue-yellow",
  displayMode: "mode-tree", // 默认模式
  bgImage: "imgs/bg/1.jpg",
  bgCount: 6,
  avatarSize: 40, // 默认头像大小
  // 🌟 升级版数据结构：支持子级 children
  items: [
    {
      name: "四大输出门派",
      desc: "追求极致暴力美学",
      nameColor: "color-pink",
      subItemNameColor: "color-black",
      nameFontSize: 30,
      subItemNameFontSize: 14,
      cardCollapsed: true,
      avatar: null,
      children: [
        //不要动这里！先暂时注释！需要我自己会打开！
        // { name: "大唐官府 - 扫地僧" },
        // { name: "狮驼岭 - 青狮王" },
      ],
    },
    {
      name: "辅助系核心",
      desc: "稳住血线是第一要素",
      nameColor: "color-blue",
      subItemNameColor: "color-black",
      nameFontSize: 30,
      subItemNameFontSize: 14,
      cardCollapsed: true,
      avatar: null,
      children: [
        //不要动这里！先暂时注释！需要我自己会打开！
        // { name: "普陀山 - 观音姐姐" },
        // { name: "化生寺 - 空度禅师" },
      ],
    },
  ],
};

// ============================
// 梦幻西游手游 多版本海报配置
// 所有封面 = 一个对象包裹，干净整洁
// 使用：posterConfigs.v1 / posterConfigs.v2 ...
// ============================

window.posterConfigs = {
  // ============================
  // 梦幻西游手游 海报配置合集 v1~v20
  // 已修复：subItemNameColor + 随机布局模式
  // 直接复制到你的 posterConfigs 对象中
  // ============================

  // v1：简约通用版（居中对称）
  v1: {
    title: "梦幻西游手游 核心攻略",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-scroll",
    titleTextStyle: "ts-gold-emboss",
    displayMode: "mode-center",
    bgImage: "imgs/bg/1.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "门派养成",
        desc: "从零到大神",
        subItemNameColor: "color-black",
        nameColor: "color-pink",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "助战搭配",
        desc: "最强组合推荐",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "装备打造",
        desc: "极品毕业指南",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "宠物选择",
        desc: "实用宠物排行",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "日常玩法",
        desc: "高效收益路线",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
    ],
  },

  // v2：巅峰竞技场（网格布局）
  v2: {
    title: "巅峰竞技场 阵容指南",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-metal",
    titleTextStyle: "ts-tech-glow",
    displayMode: "mode-grid",
    bgImage: "imgs/bg/2.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "物攻阵容",
        desc: "暴力速推流",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "法攻阵容",
        desc: "群体爆炸流",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "辅助阵容",
        desc: "稳健续航流",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "封印阵容",
        desc: "控制先手流",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
    ],
  },

  // v3：核心助战精选（阶梯对齐）
  v3: {
    title: "门派核心助战 精选",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-ice",
    titleTextStyle: "ts-ice-crystal",
    displayMode: "mode-step",
    bgImage: "imgs/bg/3.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "物理输出",
        desc: "单点爆发核心",
        subItemNameColor: "color-black",
        nameColor: "color-pink",
        nameFontSize: 28,
        children: [{ name: "首选：孙悟空" }],
      },
      {
        name: "法术输出",
        desc: "群体清场核心",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "首选：西海龙王" }],
      },
      {
        name: "治疗辅助",
        desc: "团队续航核心",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "首选：唐僧" }],
      },
      {
        name: "封印控制",
        desc: "先手限制核心",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "首选：菩提祖师" }],
      },
    ],
  },

  // v4：助战搭配大全（卡片分组）
  v4: {
    title: "全门派助战 搭配大全",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-gold",
    titleTextStyle: "ts-fire",
    displayMode: "mode-card-group",
    bgImage: "imgs/bg/4.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "大唐官府",
        desc: "物理一哥",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "孙悟空" }, { name: "杨戬" }],
      },
      {
        name: "龙宫",
        desc: "法系一哥",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "西海龙王" }, { name: "红孩儿" }],
      },
      {
        name: "普陀山",
        desc: "治疗一姐",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "观音姐姐" }, { name: "紫霞仙子" }],
      },
      {
        name: "方寸山",
        desc: "控制一哥",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "菩提祖师" }, { name: "镇元大仙" }],
      },
    ],
  },

  // v5：萌新入门指南（时间轴）
  v5: {
    title: "萌新必看 入门指南",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-mint",
    titleTextStyle: "ts-matcha",
    displayMode: "mode-timeline",
    bgImage: "imgs/bg/5.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "升级路线",
        desc: "快速冲级",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 26,
        children: [{ name: "主线优先" }, { name: "日常必做" }],
      },
      {
        name: "银币获取",
        desc: "稳定收入",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 26,
        children: [{ name: "押镖" }, { name: "师门" }],
      },
      {
        name: "金币获取",
        desc: "大额收益",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 26,
        children: [{ name: "摆摊" }, { name: "活动" }],
      },
      {
        name: "伙伴选择",
        desc: "新手首选",
        subItemNameColor: "color-black",
        nameColor: "color-pink",
        nameFontSize: 26,
        children: [{ name: "系统赠送" }, { name: "免费解锁" }],
      },
      {
        name: "宠物培养",
        desc: "过渡够用",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 26,
        children: [{ name: "海毛虫" }, { name: "泡泡" }],
      },
    ],
  },

  // v6：高难度副本（瀑布流）
  v6: {
    title: "高难度副本 通关攻略",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-metal",
    titleTextStyle: "ts-bold-black",
    displayMode: "mode-waterfall",
    bgImage: "imgs/bg/6.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "地煞星",
        desc: "高阶挑战",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "封印优先" }, { name: "保辅助" }],
      },
      {
        name: "紫薇大帝",
        desc: "团队配合",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "解封" }, { name: "加血" }],
      },
      {
        name: "神器任务",
        desc: "机制详解",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "破招" }, { name: "集火" }],
      },
    ],
  },

  // v7：梦幻门派全解（侧边分栏）
  v7: {
    title: "梦幻门派 全解析",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-emerald",
    titleTextStyle: "ts-ink",
    displayMode: "mode-column",
    bgImage: "imgs/bg/1.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "输出门派",
        desc: "伤害担当",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "大唐" }, { name: "狮驼" }],
      },
      {
        name: "法系门派",
        desc: "群伤担当",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "龙宫" }, { name: "魔王" }],
      },
      {
        name: "治疗门派",
        desc: "续航担当",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "普陀" }, { name: "化生" }],
      },
      {
        name: "封印门派",
        desc: "控制担当",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "方寸" }, { name: "女儿村" }],
      },
    ],
  },

  // v8：少女游玩手册（简约目录）
  v8: {
    title: "梦幻少女 游玩手册",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-purple",
    titleTextStyle: "ts-strawberry",
    displayMode: "mode-list",
    bgImage: "imgs/bg/2.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "时装搭配",
        desc: "绝美穿搭",
        subItemNameColor: "color-black",
        nameColor: "color-pink",
        nameFontSize: 28,
        children: [{ name: "限定" }, { name: "日常" }],
      },
      {
        name: "坐骑收集",
        desc: "可爱坐骑",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "飞行" }, { name: "陆地" }],
      },
      {
        name: "家园布置",
        desc: "温馨小屋",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "家具" }, { name: "装饰" }],
      },
      {
        name: "萌宠养成",
        desc: "可爱宠物",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "珍兽" }, { name: "神兽" }],
      },
    ],
  },

  // v9：武神坛巅峰对决（树状分级）
  v9: {
    title: "武神坛 巅峰对决",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-sunset",
    titleTextStyle: "ts-gaming",
    displayMode: "mode-tree",
    bgImage: "imgs/bg/3.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "首发阵容",
        desc: "开局压制",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "物攻" }, { name: "法攻" }],
      },
      {
        name: "替补阵容",
        desc: "战局反转",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "治疗" }, { name: "封印" }],
      },
      {
        name: "阵法选择",
        desc: "属性克制",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "天覆阵" }, { name: "虎翼阵" }],
      },
      {
        name: "战术思路",
        desc: "胜负关键",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "速攻" }, { name: "防守" }],
      },
    ],
  },

  // v10：助战图鉴（居中对称）
  v10: {
    title: "梦幻西游手游 助战图鉴",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-none",
    titleTextStyle: "ts-blue-yellow",
    displayMode: "mode-center",
    bgImage: "imgs/bg/4.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "甲级助战",
        desc: "顶级品质",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "乙级助战",
        desc: "优质品质",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
      {
        name: "丙级助战",
        desc: "新手过渡",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 30,
        avatar: null,
        children: [],
      },
    ],
  },

  // v11：物攻宠物技能（网格布局）
  v11: {
    title: "召唤灵普通技能 物攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-red",
    titleTextStyle: "ts-fire",
    displayMode: "mode-grid",
    bgImage: "imgs/bg/5.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "必杀",
        desc: "物攻暴击+10%",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "核心输出技" }, { name: "百搭易获取" }],
      },
      {
        name: "连击",
        desc: "45%概率连打2次",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "伤害降25%" }, { name: "清宠神技" }],
      },
      {
        name: "偷袭",
        desc: "免反震反击+5%伤",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "攻坚必备" }, { name: "无负面效果" }],
      },
      {
        name: "突进",
        desc: "忽视敌方少量物防",
        subItemNameColor: "color-black",
        nameColor: "color-red",
        nameFontSize: 28,
        children: [{ name: "打高防目标" }, { name: "稳定增伤" }],
      },
    ],
  },

  // v12：法攻宠物技能（阶梯对齐）
  v12: {
    title: "召唤灵普通技能 法攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-blue",
    titleTextStyle: "ts-ocean",
    displayMode: "mode-step",
    bgImage: "imgs/bg/6.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "法术暴击",
        desc: "法攻暴击+10%",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "法系核心" }, { name: "触发即爆发" }],
      },
      {
        name: "魔之心",
        desc: "法伤结果+10%",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "稳定增伤" }, { name: "无触发概率" }],
      },
      {
        name: "法术连击",
        desc: "20%概率二次攻击",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "二次伤50%" }, { name: "清场实用" }],
      },
      {
        name: "会心",
        desc: "忽视等级*0.3法防",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "打高法防目标" }, { name: "等级越高越强" }],
      },
    ],
  },

  // v13：高级物攻技能（卡片分组）
  v13: {
    title: "召唤灵高级技能 物攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-metal",
    titleTextStyle: "ts-steel",
    displayMode: "mode-card-group",
    bgImage: "imgs/bg/1.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "高级必杀",
        desc: "物攻暴击+20%",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "顶级输出技" }, { name: "爆发拉满" }],
      },
      {
        name: "高级连击",
        desc: "55%概率连打2次",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "仅降伤20%" }, { name: "性价比超高" }],
      },
      {
        name: "高级偷袭",
        desc: "免反震+10%伤",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "物攻必带" }, { name: "全方位强化" }],
      },
    ],
  },

  // v14：高级法攻技能（时间轴）
  v14: {
    title: "召唤灵高级技能 法攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-purple",
    titleTextStyle: "ts-aurora",
    displayMode: "mode-timeline",
    bgImage: "imgs/bg/2.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "高级法爆",
        desc: "法攻暴击+15%",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "法系天花板" }, { name: "暴击率翻倍" }],
      },
      {
        name: "高级魔心",
        desc: "法伤结果+20%",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "稳定增伤翻倍" }, { name: "百搭核心" }],
      },
      {
        name: "高级法连",
        desc: "30%概率二次攻击",
        subItemNameColor: "color-black",
        nameColor: "color-purple",
        nameFontSize: 28,
        children: [{ name: "触发概率提升" }, { name: "清场效率拉满" }],
      },
    ],
  },

  // v15：宠物生存技能（瀑布流）
  v15: {
    title: "召唤灵核心技能 生存篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-emerald",
    titleTextStyle: "ts-matcha",
    displayMode: "mode-waterfall",
    bgImage: "imgs/bg/3.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "神佑复生",
        desc: "20%概率复活回60%血",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "保命神技" }, { name: "忌与鬼魂共存" }],
      },
      {
        name: "吸血",
        desc: "吸收物攻伤害20%气血",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "续航必备" }, { name: "物攻宠专属" }],
      },
      {
        name: "再生",
        desc: "每回合回等级*0.8气血",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "持续回血" }, { name: "无触发条件" }],
      },
      {
        name: "强壮",
        desc: "气血上限直接+10%",
        subItemNameColor: "color-black",
        nameColor: "color-green",
        nameFontSize: 28,
        children: [{ name: "面板提升" }, { name: "所有宠通用" }],
      },
    ],
  },

  // v16：治疗水系器灵（侧边分栏）
  v16: {
    title: "治疗系 水系器灵全解析",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-ice",
    titleTextStyle: "ts-ice-crystal",
    displayMode: "mode-column",
    bgImage: "imgs/bg/4.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "柳岸花明",
        desc: "残血增疗最高25%",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "全治疗通用" }, { name: "团队救场" }],
      },
      {
        name: "天降甘霖",
        desc: "首目标疗暴+35%",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "普陀化生优选" }, { name: "单体强保" }],
      },
      {
        name: "固本培元",
        desc: "30%疗量转护盾",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "阴曹地府专属" }, { name: "防打蓝战术" }],
      },
      {
        name: "妙手回春",
        desc: "直接提升治疗强度",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "普陀天花板" }, { name: "面板直加" }],
      },
    ],
  },

  // v17：物攻主动技能（简约目录）
  v17: {
    title: "召唤灵主动技能 物攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-choco",
    titleTextStyle: "ts-bold-black",
    displayMode: "mode-list",
    bgImage: "imgs/bg/5.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "力劈华山",
        desc: "敌方物攻越低伤越高",
        subItemNameColor: "color-black",
        nameColor: "color-brown",
        nameFontSize: 28,
        children: [{ name: "点杀神技" }, { name: "克制法系" }],
      },
      {
        name: "壁垒击破",
        desc: "附加力量*0.75伤害",
        subItemNameColor: "color-black",
        nameColor: "color-brown",
        nameFontSize: 28,
        children: [{ name: "克制防御目标" }, { name: "物攻核心" }],
      },
      {
        name: "善恶有报",
        desc: "概率双倍伤或回血",
        subItemNameColor: "color-black",
        nameColor: "color-brown",
        nameFontSize: 28,
        children: [{ name: "爆发看脸" }, { name: "清宠高效" }],
      },
    ],
  },

  // v18：法攻主动技能（树状分级）
  v18: {
    title: "召唤灵主动技能 法攻篇",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-sunset",
    titleTextStyle: "ts-star",
    displayMode: "mode-tree",
    bgImage: "imgs/bg/6.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "八凶法阵",
        desc: "群体法攻引燃降法防",
        subItemNameColor: "color-black",
        nameColor: "color-orange",
        nameFontSize: 28,
        children: [{ name: "60级打3目标" }, { name: "持续掉血" }],
      },
      {
        name: "燃夜狐火",
        desc: "积3层必暴击",
        subItemNameColor: "color-black",
        nameColor: "color-orange",
        nameFontSize: 28,
        children: [{ name: "越打越强" }, { name: "群体法攻" }],
      },
      {
        name: "鹿影生花",
        desc: "30%概率三段式攻击",
        subItemNameColor: "color-black",
        nameColor: "color-orange",
        nameFontSize: 28,
        children: [{ name: "伤害递增" }, { name: "敦煌专属" }],
      },
    ],
  },

  // v19：召唤灵特色技能（居中对称）
  v19: {
    title: "召唤灵 特色专属技能",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-gold",
    titleTextStyle: "ts-gold-emboss",
    displayMode: "mode-center",
    bgImage: "imgs/bg/1.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "破竹",
        desc: "激怒状态2-6次连击",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "非激怒减伤20%" }, { name: "物攻天花板" }],
      },
      {
        name: "风舞",
        desc: "积3层疾风打3目标",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "每层加伤" }, { name: "清场神技" }],
      },
      {
        name: "捞月",
        desc: "物攻偷取敌方增益",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "附加等级*1伤" }, { name: "战术性拉满" }],
      },
      {
        name: "遗志",
        desc: "出场增12%双伤5回合",
        subItemNameColor: "color-black",
        nameColor: "color-gold",
        nameFontSize: 28,
        children: [{ name: "瞬召爆发" }, { name: "所有宠通用" }],
      },
    ],
  },

  // v20：召唤灵基础分类（网格布局）
  v20: {
    title: "召唤灵 基础分类与获取",
    titleFontSize: 32,
    isTitleBold: true,
    showBg: true,
    showTextEffect: true,
    titleBgStyle: "bg-scroll",
    titleTextStyle: "ts-ink",
    displayMode: "mode-grid",
    bgImage: "imgs/bg/2.jpg",
    bgCount: 6,
    avatarSize: 40,
    items: [
      {
        name: "野生召唤灵",
        desc: "资质成长低",
        subItemNameColor: "color-black",
        nameColor: "color-gray",
        nameFontSize: 28,
        children: [{ name: "花香香购买" }, { name: "迷宫捕捉" }],
      },
      {
        name: "普通宝宝",
        desc: "0级初始易培养",
        subItemNameColor: "color-black",
        nameColor: "color-blue",
        nameFontSize: 28,
        children: [{ name: "迷宫捕捉" }, { name: "宝宝幼儿园" }],
      },
      {
        name: "变异宝宝",
        desc: "资质优秀超稀有",
        subItemNameColor: "color-black",
        nameColor: "color-pink",
        nameFontSize: 28,
        children: [{ name: "宝宝幼儿园" }, { name: "低概率变异" }],
      },
    ],
  },
};
